# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-branch:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Fake build"
          command: "echo stuff"

workflows:
  say-hello-workflow:
    jobs:
      - build-branch
